import streamlit as st
import openai
import os

# Static API key definition (Hardcoded)
API_KEY = "API KEY"  # Replace with your OpenAI API key

# Set the OpenAI API key
openai.api_key = API_KEY  # Assigning the key to the OpenAI configuration

# Function to collect patient information for doctors
def collect_patient_info():
    st.title("Patient Information for Skin Disease Treatment")

    # Collecting basic patient information
    name = st.text_input("Patient's Name")
    age = st.number_input("Patient's Age", min_value=1, step=1)
    gender = st.selectbox("Patient's Gender", ["Male", "Female", "Other"])

    # Collecting skin-related information
    skin_type = st.selectbox("Patient's Skin Type", ["Dry", "Oily", "Combination", "Normal"])
    symptoms = st.text_area("Describe the patient's skin disease symptoms")
    severity = st.selectbox("Severity of the symptoms", ["Mild", "Moderate", "Severe"])
    duration = st.number_input("Duration of symptoms (in days)", min_value=1, step=1)

    # Collecting medical history information
    allergies = st.radio("Does the patient have any allergies?", ["Yes", "No"])
    if allergies == "Yes":
        allergy_details = st.text_area("List the patient's allergies")
    else:
        allergy_details = "None"

    # Return the collected information as a dictionary
    patient_info = {
        "name": name,
        "age": age,
        "gender": gender,
        "skin_type": skin_type,
        "symptoms": symptoms,
        "severity": severity,
        "duration": duration,
        "allergies": allergy_details,
    }
    return patient_info

# Function to generate insights for doctors using OpenAI
def generate_openai_insights(patient_info):
    prompt = f"""
    Patient Information:
    - Name: {patient_info['name']}
    - Age: {patient_info['age']}
    - Gender: {patient_info['gender']}
    - Skin Type: {patient_info['skin_type']}
    - Symptoms: {patient_info['symptoms']}
    - Severity: {patient_info['severity']}
    - Duration of Symptoms: {patient_info['duration']} days
    - Allergies: {patient_info['allergies']}

    Based on this information, suggest some basic treatment plans or recommendations for a doctor to consider.
    """

    # Generate a response from OpenAI
    response = openai.Completion.create(
        engine="babbage-002",
        prompt=prompt,
        max_tokens=150  # Adjust token count based on desired response length
    )

    return response.choices[0].text

# Main function to run the Streamlit application
def main():
    # Collect patient information
    patient_info = collect_patient_info()

    # Button to generate OpenAI insights
    if st.button("Generate Treatment Suggestions"):
        # Get insights from OpenAI
        insights = generate_openai_insights(patient_info)
        
        # Display the OpenAI-generated insights
        st.subheader("Suggested Treatment Plans")
        st.markdown(insights)

        # Disclaimer for safety
        st.warning("These suggestions are generated by AI and should be reviewed by a licensed doctor before implementation.")

# Run the Streamlit application
if __name__ == "__main__":
    main()
